<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J7DCQRE" failures="1" tests="2" name="Test" time="3.311" errors="0" timestamp="2024-07-29T18:11:12 IST">
  <testcase classname="testng.FirstTest" name="testSub" time="3.23"/>
  <testcase classname="testng.FirstTest" name="testAdd" time="3.23">
    <failure type="java.lang.AssertionError" message="expected [2] but found [24]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [24]
at testng.FirstTest.testAdd(FirstTest.java:15)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testAdd -->
</testsuite> <!-- Test -->
